### ISSUE TITLE
Parser.py missing AdapterParser in cutadapt

### ISSUE THREAD

**Issue by lucascpantaleao** [mhalushka/miRge3.0#45]
Hello,

just getting an error every time I run miRge3.0 as it seems that AdapterParser is not in parser.py so digest.py cannot import it.

Traceback (most recent call last):
  File "/usr/local/bin/miRge3.0", line 5, in <module>
    from mirge.__main__ import main
  File "/home/lucascp/.local/lib/python3.8/site-packages/mirge/__main__.py", line 16, in <module>
    from mirge.libs.digest import baking
  File "/home/lucascp/.local/lib/python3.8/site-packages/mirge/libs/digest.py", line 11, in <module>
    from cutadapt.parser import AdapterParser
ImportError: cannot import name 'AdapterParser' from 'cutadapt.parser' (/home/lucascp/.local/lib/python3.8/site-packages/cutadapt/parser.py)

**Comment by lucascpantaleao** [comment]
Hi Arun, thought it would be the case.

Forced reinstallation and all working now.

Cheers mate.

**Comment by johannornth** [comment]
Thank you so much! I was having the same problem and this worked for me

**Comment by arunhpatil** [comment]
Hi @johannornth,

We have fixed this bug, and are currently revising few minor suggestions before the next release. This release will be tested and made available soon. Thank you. 

Arun

**Comment by Adrian-Zet** [comment]
Hello, I have the same exact issue but with the conda installation.

Can you please provide a fix for the conda version?
I tried the fix above and it didn't work

**Comment by arunhpatil** [comment]
Hi @Adrian-Zet, 

We have recently fixed this bug and it is available in the latest release. Please follow the lines below and we should be able to solve the issue:

- Let us first uninstall any versions of mirge3 from the system and once uninstalled check if the `miRge3.0 -h ` says `command not found`
`python3.8 -m pip uninstall mirge3`
- What version of Python are you using?
- I recommend you create an environment as shown below with python3.8 
 `conda create -n "mirge38" python=3.8`
 `conda activate mirge38`
 `conda install -c bioconda mirge3`
- This should fix the problem, please let us know if the error still persists. If the error is not resolved, then please mention the cutadapt version. 

I hope this helps. 

Thank you,
Arun.

**Comment by Adrian-Zet** [comment]
Dear Arun,

I just did the steps you mentioned in the exact order and the error still persists:

(mirge38) saia@fp84:~$ miRge3.0 -h
Traceback (most recent call last):
  File "/export/home/math/saia/mambaforge/envs/mirge38/bin/miRge3.0", line 6, in <module>
    from mirge.__main__ import main
  File "/export/home/math/saia/mambaforge/envs/mirge38/lib/python3.8/site-packages/mirge/__main__.py", line 17, in <module>
    from mirge.libs.digest import baking
  File "/export/home/math/saia/mambaforge/envs/mirge38/lib/python3.8/site-packages/mirge/libs/digest.py", line 12, in <module>
    from cutadapt.parser import make_adapters_from_specifications
ImportError: cannot import name 'make_adapters_from_specifications' from 'cutadapt.parser' (/export/home/math/saia/.local/lib/python3.8/site-packages/cutadapt/parser.py)

Below are the cutadapt version and it's path:

(mirge38) saia@fp84:~$ cutadapt
This is cutadapt 3.4 with Python 3.8.13
Command line parameters:
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: You did not provide any input file names. Please give me something to do!
(mirge38) saia@fp84:~$ which cutadapt
/export/home/math/saia/mambaforge/envs/mirge38/bin/cutadapt

I'm using python3.8 both outside of conda and in the mirge38 conda environment (as installed by your command).

**Comment by arunhpatil** [comment]
Hi @Adrian-Zet,

Thank you for trying those. This issue is mainly with the new version of cutadapt where they have changed the name of the internal function. The recent miRge3.0 update accomodates this change, however, conda installation looks at other dependencies and install the version which best suits your machine. This however has led to the installation of older version of cutadapt. So, to resolve this, we need to simply install the latest version of cutadapt which is (4.1 as of today).

To install the latest version:
`conda install -c bioconda cutadapt==4.1`

Please let me know if this solves the error. 
Thank you,
Arun.

**Comment by Adrian-Zet** [comment]
Dear Arun,

I tried to install that specific version of cutadapt. Yet it seems it keeps installing the 3.4 version no matter what I do. I tried cutadapt==4.1 ; cutadapt=4.1 I tried to perform a conda clean --all with no avail. Every trial was performed in a clean environment. I think the problem might be related to the conda installation, it seems to always install the 3.4 cutadapt version no matter what I try. I will look into it and come back after I manage to find a fix for installing 4.1.

Thank you,
Adrian.

**Comment by arunhpatil** [comment]
Hi @Adrian-Zet,

Sorry for the inconvenience, conda installation is based on many dependencies (especially libc etc.). I have modified the `digest.py` and `digestEC.py` scripts with a try-exception block to bypass this error. I have attached these scripts in the zip file. You can download these scripts and replace the scripts in the libs folder (below path). This should work. Please let me know if you encounter any error following this update. 

Path: 
/export/home/math/saia/mambaforge/envs/mirge38/lib/python3.8/site-packages/mirge/libs/

Command:
```
unzip quickfix.zip
cd quickfix
cp digest* /export/home/math/saia/mambaforge/envs/mirge38/lib/python3.8/site-packages/mirge/libs/
```
(Note: for other users seeing this solution, please change the path according to your miRge3.0 installation path)

[quickfix.zip](https://github.com/mhalushka/miRge3.0/files/9996302/quickfix.zip)

Thank you,
Arun.

**Comment by Adrian-Zet** [comment]
Dear Arun,

Thank you very much for the help and the patience! The fix you provided seems to have done the trick. The program works fine now. 
I believe I need to keep this fix whenever I will install miRge3.0 with conda again, right?

Have a wonderful Sunday!
Adrian.

**Comment by arunhpatil** [comment]
Hi @Adrian-Zet,

I am glad it workedout and I will update this new patch on pip and conda (you may skip saving these files for future installations). Having said that, with newer dependencies, miRge3.0 will no longer support Python version `<3.6`. Since you have Python 3.8, it worked great. 

Thanks and you as well have a good weekend. 
Arun

**Comment by arunhpatil** [comment]
Hi @Adrian-Zet, 

Can you execute miRge3.0 with a test dataset?

I made this patch available, however, another machine had an error with `error_rate` parameter. If you encountered similar error on a test run, please let us know.  

Thank you,
Arun.

**Comment by Cristinex** [comment]
Thank you @arunhpatil for your continuous efforts to develop this tool. I come across this issue again when using either 0.1.2, 0.1.3.

**Comment by arunhpatil** [comment]
Hi @Cristinex,

Thank you. I guess this could be due to the installation of previous versions of Cutadapt. Can you check cutadapt version? and upgrade to >= 4.0 (preferred 4.2). Also, are you using Mac? 

I have limited access currently due to my travells and will be back to answer any questions by July 01. Please feel free to leave your queries here and I will try my best to get back. 

Thank you,
Arun.
